[application]
name = "WonderScore"

[web.app]

# HTML title tag content
title = "wonder-score"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "fr.ijkl.wonderscore"
publisher = "J.Girardet"
icon = ["assets/icon-256.png"]
copyright = "MIT"
category = ""
short_description = "Minimalist score counter for Seven Wonders"
long_description = "Minimalist score counter for Seven Wonders"
